/**
 * @file savedobjs.c
 *
 * Generated by mksaveobjsarray.py from CSV file ..\app\device_profile\DPMU_001.csv
 *
 * saveObj[] contains filtered objects from CSV file.
 *
 * Run "python mksaveobjsarray.py -a" to include all objects from CSV.
 *
 * Date: 2024-02-06 02:02
 */

#include "savedobjs.h"

const save_od_t saveObj[] = {
    // --- Communication Parameters ---
    { 0x1017, 0x00,  TWO_BYTES,     0x03E8 },    // Producer Heartbeat Time
    { 0x1029, 0x01,   ONE_BYTE,       0x01 },    // Error behaviour Communication Error
    { 0x1029, 0x02,   ONE_BYTE,       0x00 },    // Error behaviour Specific Error Class 
    { 0x1800, 0x03,  TWO_BYTES,     0x1388 },    // Transmit PDO IO Inhibit Time
    { 0x1800, 0x05,  TWO_BYTES,     0x0000 },    // Transmit PDO IO Event Timer

    // --- Manufacturer Defined Parameters ---
    { 0x3000, 0x01,   ONE_BYTE,       0xA7 },    // DC_Bus_Voltage Min_Allowed_DC_Bus_Voltage
    { 0x3000, 0x02,   ONE_BYTE,       0xC1 },    // DC_Bus_Voltage Max_Allowed_DC_Bus_Voltage
    { 0x3000, 0x03,   ONE_BYTE,       0xB4 },    // DC_Bus_Voltage Target_Voltage_At_DC_Bus
    { 0x3000, 0x04,   ONE_BYTE,       0x3C },    // DC_Bus_Voltage VDC_Bus_Short_Circuit_Limit
    { 0x3000, 0x05,   ONE_BYTE,       0x01 },    // DC_Bus_Voltage VDROOP
    { 0x3001, 0x00,   ONE_BYTE,       0x30 },    // ESS_Current
    { 0x3200, 0x01,   ONE_BYTE,       0x00 },    // Temperature DPMU_Temperature_Max_Limit
    { 0x3200, 0x03,   ONE_BYTE,       0x00 },    // Temperature DPMU_Temperature_High_Limit
    { 0x3301, 0x00,  TWO_BYTES,     0x0000 },    // Maximum_Allowed_Load_Power
    { 0x3302, 0x01,  TWO_BYTES,     0x0000 },    // Power_Budget_DC_Input Available_Power_Budget_DC_Input
    { 0x3400, 0x01,   ONE_BYTE,       0x5A },    // Energy_Bank_Summary Max_Voltage_Applied_To_Energy_Bank
    { 0x3400, 0x02,   ONE_BYTE,       0x1E },    // Energy_Bank_Summary Min_Voltage_Applied_To_Energy_Bank
    { 0x3400, 0x04,  TWO_BYTES,     0x002D },    // Energy_Bank_Summary Safety_Threshold_State_of_Charge

    // --- Application Parameters ---
};

// Used in file canopen_sdo_download_indices.c when accessing external flash.
save_od_t savedData[sizeof(saveObj) / sizeof(save_od_t)];

uint32_t get_num_saved_objs(void)
{
    return sizeof(saveObj) / sizeof(save_od_t);
}
