/*
 * static indication definitions for DPMU_001 - generated by CANopen DeviceDesigner 3.8.0
 * tis jan 30 13:14:11 2024
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_INDICATION
#define GEN_INDICATION 1

/* 
   There are not any static indication functions defined.
   If there were some, they would be declared here. 
 */

#endif /* GEN_INDICATION*/
