/*
 * initialization_app.h
 *
 *  Created on: 28 de mai de 2024
 *      Author: gferreira
 */


#ifndef APP_INC_INITIALIZATION_APP_H_
#define APP_INC_INITIALIZATION_APP_H_

#include "stdint.h"

typedef enum DPMU_Initialization_Vars
{
    IDX_DPMU_VAR_DATE_AND_TIME = 0,
    IDX_DPMU_VAR_AVAILABLE_POWER_BUDGET_DC_INPUT,
    IDX_DPMU_VAR_MAXIMUM_ALLOWED_LOAD_POWER,
    IDX_DPMU_VAR_ESS_CURRENT,
    IDX_DPMU_VAR_MAX_VOLTAGE_ENERGY_CELL,
    IDX_DPMU_VAR_MIN_VOLTAGE_ENERGY_CELL,
    IDX_DPMU_VAR_MAX_VOLTAGE_APPLIED_TO_STORAGE_BANK,
    IDX_DPMU_VAR_CONSTANT_VOLTAGE_THRESHOLD,
    IDX_DPMU_VAR_MIN_ALLOWED_STATE_OF_CHARGE_OF_ENERGY_BANK,
    IDX_DPMU_VAR_PRECONDITIONAL_THRESHOLD,
    IDX_DPMU_VAR_SAFETY_THRESHOLD_STATE_OF_CHARGE,
    IDX_DPMU_VAR_MAX_ALLOWED_DC_BUS_VOLTAGE,
    IDX_DPMU_VAR_TARGET_VOLTAGE_AT_DC_BUS,
    IDX_DPMU_VAR_MIN_ALLOWED_DC_BUS_VOLTAGE,
    IDX_DPMU_VAR_VDC_BUS_SHORT_CIRCUIT_LIMIT,
    IDX_DPMU_VAR_MAX_ALLOWED_DPMU_TEMPERATURE,
    IDX_DPMU_VAR_DPMU_TEMPERATURE_HIGH_LIMIT,
    IDX_DPMU_VAR_DPMU_POWER_SOURCE_TYPE,
    IDX_DPMU_VAR_COUNT
} DPMU_Initialization_Vars_t;

extern bool DPMUAppInfoInitialized[IDX_DPMU_VAR_COUNT];

void CheckDPMUAppInfoInitializeVars(DPMU_Initialization_Vars_t DPMUappVarIdx );
void ResetDPMUAppInfoInitializeVars();
bool VerifyAppInfoVarInitialized( DPMU_Initialization_Vars_t DPMUappVarIdx );
void InitializeCPU1ToCPU2SharedVariables( void );

#endif /* APP_INC_INITIALIZATION_APP_H_ */
